dbt/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from dbt import settings

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'dbt.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'', include('setlist.urls')),
                       url(r'^adminactions/', include('adminactions.urls')),
                       url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                           document_root=settings.STATIC_ROOT)

setlist/models.py
from django.db import models
from django.db.models.signals import post_save
from django.utils.safestring import mark_safe
import re
import pprint
# Create your models here.

def render_notes(str):
  if str.strip() == "":
    return ""
  str = str.replace('\r', '')
  paras = str.split('\n\n')
  out = []
  for p in paras:
    r = p.strip()
    r = re.sub(r'\{(.*?)\}', r'<span class="person">\1</span>', r)
    out.append('<p class="notes">' + r + '</p>')
  return mark_safe('\n'.join(out))


class Album(models.Model):
  name = models.CharField(max_length=255)
  release_date = models.DateField()
  cover = models.FileField(null=True, blank=True)
  notes = models.TextField(blank=True, default='')

  def rendered_notes(self):
    return render_notes(self.notes)

  def __str__(self):
    return self.name


class Person(models.Model):
  name = models.CharField(max_length=255)
  notes = models.TextField(blank=True, default='')

  def rendered_notes(self):
    return render_notes(self.notes)

  def __str__(self):
    return self.name


def slug_song(title):
  m = re.match(r'(\d+\. )?(.*)', title).group(2).lower()
  m = m.replace('&', 'and')
  m = m.replace('the ', ' ')

  return filter(lambda x: x.isalpha(), m)


class Song(models.Model):
  name = models.CharField(max_length=255)
  album = models.ForeignKey(Album, blank=True, default=None, null=True, db_index=True)
  notes = models.TextField(blank=True, default='')
  author = models.ForeignKey(Person, null=True, blank=True)
  slug = models.CharField(editable=False, max_length=255, default='')

  def rendered_notes(self):
    return render_notes(self.notes)

  def save(self, *args, **kwargs):
    self.name = re.match(r'(\d+\. )?(.*)', self.name).group(2)
    self.name = self.name.replace('&', 'and')

    self.slug = slug_song(self.name)
    super(Song, self).save(*args, **kwargs)

  def __str__(self):
    if self.author != None:
      return self.name + " / " + self.author.name
    else:
      return self.name

  class Meta:
    ordering = ('name',)


class Venue(models.Model):
  name = models.CharField(max_length=255)
  city = models.TextField(db_index=True)
  state = models.CharField(max_length=255, default='', db_index=True)
  notes = models.TextField(blank=True, default='')

  def rendered_notes(self):
    return render_notes(self.notes)

  def __str__(self):
    return self.name + " (" + self.city + ", " + self.state + ")"

  class Meta:
    ordering = ('name', 'state')


class MasterTour(models.Model):
  name = models.CharField(max_length=120)

  def __str__(self):
    return self.name


class Tour(models.Model):
  name = models.CharField(max_length=120)
  start_date = models.DateField(default='2050-01-01', editable=False)
  notes = models.TextField(blank=True, default='')
  master_tour = models.ForeignKey(MasterTour, null=True, db_index=True)

  def rendered_notes(self):
    return render_notes(self.notes)

  def __str__(self):
    try:
      return self.master_tour.name + ' - ' + self.name
    except:
      return self.name


class Show(models.Model):
  venue = models.ForeignKey(Venue, db_index=True)
  tour = models.ForeignKey(Tour, db_index=True)
  date = models.DateField(db_index=True)
  setlist = models.TextField(blank=True, default='')
  notes = models.TextField(blank=True, default='')
  source = models.TextField(blank=True, default='')


  def rendered_notes(self):
    return render_notes(self.notes)

  def __str__(self):
    return str(self.tour) + ": " + self.date.isoformat() + " " + str(self.venue)

  def shortname(self):
    return self.date.isoformat() + " " + str(self.venue)


class SetlistSong(models.Model):
  show = models.ForeignKey(Show, db_index=True)
  song = models.ForeignKey(Song, db_index=True)
  order = models.IntegerField()
  pos = models.FloatField(default=0.0)
  segue = models.BooleanField(default=False)
  set = models.CharField(max_length=1, choices=[('1', '1st Set'), ('2', '2nd Set'), ('3', '3rd Set'), ('E', 'Encore')])
  notes = models.TextField(blank=True, default='')

  def rendered_notes(self):
    return render_notes(self.notes)

  def __str__(self):
    return str(self.order) + ": " + self.song.name

  class Meta:
    ordering = ('order',)


def saveSetlistFromShow(sender, instance=False, **kwargs):
  SetlistSong.objects.filter(show=instance).delete()

  set = 1
  order = 0
  tot = 0.0
  for line in instance.setlist.split('\n'):
    x = line.strip()
    if x != '---' and x != '':
      tot += 1.0
  for line in instance.setlist.split('\n'):
    x = line.strip().split('|')
    if x[0] == '':
      set = 'E'
      continue
    elif x[0] == '---':
      set += 1
      continue
    else:
      segue = False
      if x[0][-1] == '>':
        x[0] = x[0][:-2]
        segue = True

      song, created = Song.objects.get_or_create(slug=slug_song(x[0]), defaults={'name': x[0]})
      order += 1
      notes = ''
      if len(x) > 1:
        notes = x[1]
      if tot == 1.0:
        tot = 2.0
        order = 2.0
      sls = SetlistSong(show=instance, song=song, order=order, set=str(set), notes=notes, segue=segue,
                        pos=(order - 1.0) / (tot - 1.0))
      sls.save()


post_save.connect(saveSetlistFromShow, sender=Show)

templates/analysis.jinja
{% extends "base.jinja" %}

{% block title %}{{ tour.name }} Tour Analysis{% endblock %}
{% block content %}
  <h1>Analysis for <a href="/tour/{{ tour.id }}">{{ tour }}</a></h1>
  <table>

    <tbody>
    {% for album in data %}
      <tr>
        <td colspan="4"><h3>{{ album[0] }}</h3></td>
      </tr>
      <tr>
        <th>Song</th>
        <th>Played</th>
        <th>Opener</th>
        <th>Closer</th>
      </tr>
      {% for song in album[1] %}

        <tr>
          <td><a href="/song/{{ song[4] }}">{{ song[0] }}</a></td>
          <td class="cell{{ song[1] }}x">{{ song[1] }}</td>
          <td class="cell{{ song[1] }}x">{{ song[2] }}</td>
          <td class="cell{{ song[1] }}x">{{ song[3] }}</td>
        </tr>
      {% endfor %}
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/base.jinja
<!doctype html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  {% block meta %}{% endblock meta %}
  {% block base_title %}
    <title>{% block title %} Home{% endblock title %} :: 26miledrive.com - Drive-By Truckers Tour Data</title>
  {% endblock base_title %}

  {# Base Foundation CSS #}
  <link rel="stylesheet" href="/static/foundation/css/normalize.css"/>
  <link rel="stylesheet" href="/static/foundation/css/foundation.min.css"/>


  {# Custom CSS #}
  <link rel="stylesheet" type="text/css" href="/media/css/custom.css?ver=8"/>

  {# Override if you need another version of modernizr #}
  <script src="/static/foundation/js/vendor/modernizr.js"></script>


  {# Custom head JS #}
  {% block head_js %}{% endblock head_js %}
</head>
<body {% block body_attr %}{% endblock body_attr %}>
{# Main content goes here #}


<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">26miledrive.com</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><a href="mailto:tylere@gmail.com">Contact Tyler (Site Admin)</a></li>
    </ul>
    <ul class="left">
      <li class="has-dropdown">
        <a href="#">Tours</a>
        <ul class="dropdown">
          {% for mt in tours %}
            <li class="has-dropdown not-click"><a href="#">{{ mt.name }}</a>
              <ul class="dropdown">
                {% for leg in mt['legs'] %}
                  <li><a href="/tour/{{ leg['id'] }}">{{ leg['name'] }}</a></li>
                {% endfor %}
              </ul>
            </li>
          {% endfor %}
        </ul>
      </li>
      <li class="has-dropdown">
        <a href="#">Albums &amp; Songs</a>
        <ul class="dropdown">
          {% for album in albums %}
            <li class="has-dropdown not-click"><a href="#">{{ album.name }}</a>
              <ul class="dropdown">
                {% for song in album['songs'] %}
                  <li><a href="/song/{{ song['id'] }}">{{ song['name'] }}</a></li>
                {% endfor %}
              </ul>
            </li>
          {% endfor %}
        </ul>
      </li>
    </ul>
  </section>

</nav>

<section role="main">
  <div class="row">
    <div class="small-12 columns">
      {% block content %}
        This is a default body
      {% endblock %}
    </div>
  </div>
</section>
<script>
  (function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function () {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date();
    a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

  ga('create', 'UA-49185903-1', '26miledrive.com');
  ga('send', 'pageview');

</script>

{# Override if you need another version of jQuery #}


<script src="/static/foundation/js/vendor/jquery.js"></script>


<script src="/static/foundation/js/foundation.min.js"></script>


{# Custom JS #}
{% block body_js %}{% endblock body_js %}

{# Init Foundation #}
{% block foundation_js_init %}
  <script>
    $(document).foundation();
  </script>
{% endblock foundation_js_init %}
</body>
</html>


templates/home.jinja
{% extends "base.jinja" %}

{% block title %}Recent Shows{% endblock %}
{% block content %}
  <h2>Please pardon our dust...</h2>
  <p>With the recent closure of oneofthesedays.org, I've kicked my work on this site into high gear, but it's still not
    quite where I'd like to be in terms of navigational ease. I'm working on it!</p>
  <h1>Recent shows</h1>

  <p>This view shows a list of recent shows from easy viewing. Click the show to set the setlist. Click the tour name to
    see the song matrix for that tour</p>


  <table>
    <thead>
    <tr>
      <th>Show</th>
      <th>Tour</th>
    </tr>

    </thead>
    <tbody>
    {% for show in shows %}
      <tr>
        <td><a href="/show/{{ show.id }}">{{ show.date }} - {{ show.venue.name }}
          - {{ show.venue.city }}, {{ show.venue.state }} </a></td>
        <td><a href="/tour/{{ show.tour.id }}">{{ show.tour }}</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

templates/matrix.html
{% extends "base.html" %}


{% block content %}
  <h1>Song Matrix for {{ tour.name }} Tour</h1>
  {{ tour.rendered_notes }}
  <dl class="sub-nav">
    <dt>Order By:</dt>
    {% for sort in sorts %}
      <dd
              {% if order == sort.0 %}
                class="active"
              {% endif %}
              ><a href="/tour/{{ tour.id }}?order={{ sort.0 }}">{{ sort.1 }}</a></dd>
    {% endfor %}
  </dl>
  <table>
    <thead>
    <tr>
      <th>Show Date<br/>
        <small>Click date for setlist</small>
      </th>
      <th>Played</th>
      {% for show in shows %}
        <th class="centered">
          <a href="/show/{{ show.id }}">
            {{ show.date.year }}<br/>
            {{ show.date.month }}/{{ show.date.day }}</a>
        </th>
      {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for song in songs %}
      <tr>
        <td><a href="/song/{{ song.id }}">{{ song.name }}</a></td>
        <td>{{ song.count }}</td>
        {% for show in song.shows %}
          <td class="cell{{ show|lower }}">{{ show }}</td>
        {% endfor %}
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

templates/matrix.jinja
{% extends "base.jinja" %}

{% block title %}{{ tour.name }} Tour{% endblock %}
{% block content %}
  <h1>Song Matrix for {{ tour }} </h1>
  {{ tour.rendered_notes() }}

  <p>This view shows a grid based representation of the songs palyed each night on this tour, as well as running counts
    of how many shows in a row each song is played.</p>

  <p><strong><a href="/tour-analysis/{{ tour.id }}">New: Album-by-album analysis for this tour</a></strong></p>
  <dl class="sub-nav">
    <dt>Order By:</dt>
    {% for sort in sorts %}
      <dd
              {% if order == sort.0 %}
                class="active"
              {% endif %}
              ><a href="/tour/{{ tour.id }}?order={{ sort.0 }}">{{ sort.1 }}</a></dd>
    {% endfor %}
  </dl>
  </div>
  <div class="small-12 columns">
    <table class="matrix">
      <thead>
      <tr>
        <th>Show Date<br/>
          <small>Click date for setlist</small>
        </th>
        <th>Played</th>
        {% for show in shows %}
          <th class="centered">
            <a href="/show/{{ show.id }}">
              {{ show.date.year }}<br/>
              {{ show.date.month }}/{{ show.date.day }}</a>
          </th>
        {% endfor %}
      </tr>
      <tr>
        <th></th>
        <th class="align: right;">
          <small># Songs</small>
        </th>
        {% for show in shows %}
          <td class="centered">{{ show.setlistsong_set.count() }}</td>
        {% endfor %}
      </tr>

      </thead>
      <tbody>
      {% for song in songs %}
        <tr>
          <td><a href="/song/{{ song.id }}">{{ song.name }}</a></td>
          <td>{{ song.count }}</td>
          {% for show in song.shows %}
            <td class="cell{{ show|lower }}">{{ show }}</td>
          {% endfor %}
        </tr>
      {% endfor %}
      </tbody>
    </table>

{% endblock %}

templates/show.html
{% extends "base.html" %}

{% block content %}

  <h1><a href="/tour/{{ show.tour_id }}">{{ show.tour.name }}</a> Tour - {{ show.date.isoformat }}</h1>
  <h2>{{ show.venue.name }}</h2>
  <h3>{{ show.venue.city }}, {{ show.venue.state }}</h3>
  {{ show.rendered_notes }}

  <table>
    <thead>
    <tr>
      <th>#</th>
      <th>Set</th>
      <th>Song</th>
      <th>Notes</th>
    </tr>
    </thead>

    {% for song in songs %}
      <tr>
        <td>{{ song.order }}.</td>
        <td>{{ song.set }}</td>
        <td><a href="/song/{{ song.song.id }}">{{ song.song.name }}</a>{% if song.segue %} &gt; {% endif %}</td>
        <td class="notes">{{ song.rendered_notes }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/show.jinja
{% extends "base.jinja" %}
{% block title %}{{ show.date.isoformat() }} - {{ show.venue.name }}{% endblock %}
{% block content %}

  <h1><a href="/tour/{{ show.tour_id }}">{{ show.tour }}</a> - {{ show.date.isoformat() }}</h1>
  <h2>{{ show.venue.name }}</h2>
  <h3>{{ show.venue.city }}, {{ show.venue.state }}</h3>
  {{ show.rendered_notes() }}

  <table>
    <thead>
    <tr>
      <th>#</th>
      <th>Set</th>
      <th>Song</th>
      <th>Notes</th>
    </tr>
    </thead>

    {% for song in songs %}
      <tr>
        <td>{{ song.order }}.</td>
        <td>{{ song.set }}</td>
        <td><a href="/song/{{ song.song.id }}">{{ song.song.name }}</a>{% if song.segue %} &gt; {% endif %}</td>
        <td class="notes">{{ song.rendered_notes() }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/song.html
{% extends "base.html" %}

{% block content %}

  <h1>{{ song.name }}</h1>
  <h2>{{ song.author.name }}</h2>
  <h3>{{ song.album.name }}</h3>
  <p>{{ song.notes }}</p>

  <table>
    <thead>
    <tr>
      <th>Tour</th>
      <th>Date</th>
      <th>Venue</th>
      <th>Location</th>
    </tr>
    </thead>

    {% for show in shows %}
      <tr>
        <td><a href="/tour/{{ show.tour.id }}">{{ show.tour.name }}</a></td>
        <td><a href="/show/{{ show.id }}">{{ show.date.isoformat }}</a></td>
        <td>{{ show.venue.name }}</td>
        <td>{{ show.venue.city }}, {{ show.venue.state }}</td>

      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/song.jinja
{% extends "base.jinja" %}
{% block title %}{{ song.name }} Tour{% endblock %}
{% block content %}

  <h1>{{ song.name }}</h1>
  <h2>{{ song.author.name }}</h2>
  <h3>{{ song.album.name }}</h3>
  <p>{{ song.rendered_notes() }}</p>

  <table>
    <thead>
    <tr>
      <th>Tour</th>
      <th>Date</th>
      <th>Venue</th>
      <th>Location</th>
    </tr>
    </thead>

    {% for show in shows %}
      <tr>
        <td><a href="/tour/{{ show.tour.id }}">{{ show.tour }}</a></td>
        <td><a href="/show/{{ show.id }}">{{ show.date.isoformat() }}</a></td>
        <td>{{ show.venue.name }}</td>
        <td>{{ show.venue.city }}, {{ show.venue.state }}</td>

      </tr>
    {% endfor %}
  </table>
{% endblock %}